### ISSUE TITLE
SystemError raised for invalid function signature in object_hook callback.

### ISSUE THREAD

**Issue by kohlerjl** [agronholm/cbor2#205] opened 2024-01-05 00:00 UTC
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### cbor2 version

5.5.1

### Python version

3.8

### What happened?

If the function signature of the `object_hook` callback is incorrect, `loads` raises "SystemError: <built-in function loads> returned a result with an error set".

I would expect the original TypeError to be propagated up. This issue does not seem to affect the `default` callback in `dumps`

### How can we reproduce the bug?

```
import cbor2
import pytest

def test_invalid_object_hook():
    def invalid_object_hook(obj):
        return obj

    obj = {
        'a': 1,
        'hello': 'world',
        'obj': {
            'foo': 'bar'
        },
    }
    data = cbor2.dumps(obj)
    with pytest.raises(TypeError):
        cbor2.loads(data, object_hook=invalid_object_hook)
```

**Comment by agronholm** [comment] 2024-01-14 11:53
I can't reproduce this on master, so I'm closing this. Let me know if this was in error.

**Closed by agronholm** 2024-01-14 11:53 UTC
Labels: bug

**Comment by kohlerjl** [comment] 2024-01-16 07:08
You're right, I just tested on master and confirmed it works. Must have already been fixed by other changes since the last release. Thanks for taking a look.
